---
# uat - single data center.
# node_id is PINNED per KRaft node and unique across controllers and brokers.
all:
  children:
    env_uat:
      children:
        kafka_controller:
          hosts:
            flrutkedapkrf01.thynet.thy.com: { node_id: 1, ansible_host: 10.80.111.61 }
            flrutkedapkrf02.thynet.thy.com: { node_id: 2, ansible_host: 10.80.111.62 }
            flrutkedapkrf03.thynet.thy.com: { node_id: 3, ansible_host: 10.80.111.63 }
        kafka_broker:
          hosts:
            flrutkedapbkr01.thynet.thy.com: { node_id: 101, ansible_host: 10.80.111.64 }
            flrutkedapbkr02.thynet.thy.com: { node_id: 102, ansible_host: 10.80.111.65 }
            flrutkedapbkr03.thynet.thy.com: { node_id: 103, ansible_host: 10.80.111.66 }
        schema_registry:
          hosts:
            flrutkedapsch01.thynet.thy.com: { ansible_host: 10.80.111.69 }
            flrutkedapsch02.thynet.thy.com: { ansible_host: 10.80.111.70 }
        kafka_connect:
          hosts:
            flrutkedapcnt01.thynet.thy.com: { ansible_host: 10.80.111.67 }
            flrutkedapcnt02.thynet.thy.com: { ansible_host: 10.80.111.68 }
        kafka_rest:
          hosts:
            flrutkedaprpr01.thynet.thy.com: { ansible_host: 10.80.111.72 }
            flrutkedaprpr02.thynet.thy.com: { ansible_host: 10.80.111.73 }
        control_center_next_gen:
          hosts:
            flrutkedapcct01.thynet.thy.com: { ansible_host: 10.80.111.71 }
